// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVDAsAiL_scGd3Xhw8-yzI9fGUYEaAIjw',
    appId: '1:950206893906:web:86d1bc3e7eba8a1f32f48b',
    messagingSenderId: '950206893906',
    projectId: 'lab10-dd5fb',
    authDomain: 'lab10-dd5fb.firebaseapp.com',
    storageBucket: 'lab10-dd5fb.appspot.com',
    measurementId: 'G-KHV1E5R5E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqcDDrnJiwcTTGZGrvcHjvzw8kC8-eQLg',
    appId: '1:950206893906:android:83ffd184241e525b32f48b',
    messagingSenderId: '950206893906',
    projectId: 'lab10-dd5fb',
    storageBucket: 'lab10-dd5fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4xjMOmsYBXGmWZquvkclObCuZTzEVrKM',
    appId: '1:950206893906:ios:a8e083029306775732f48b',
    messagingSenderId: '950206893906',
    projectId: 'lab10-dd5fb',
    storageBucket: 'lab10-dd5fb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4xjMOmsYBXGmWZquvkclObCuZTzEVrKM',
    appId: '1:950206893906:ios:a8e083029306775732f48b',
    messagingSenderId: '950206893906',
    projectId: 'lab10-dd5fb',
    storageBucket: 'lab10-dd5fb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVDAsAiL_scGd3Xhw8-yzI9fGUYEaAIjw',
    appId: '1:950206893906:web:ec49629cf5930e4332f48b',
    messagingSenderId: '950206893906',
    projectId: 'lab10-dd5fb',
    authDomain: 'lab10-dd5fb.firebaseapp.com',
    storageBucket: 'lab10-dd5fb.appspot.com',
    measurementId: 'G-619L3P31LS',
  );
}
